// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqY7Eo6UOMRBtxL4x5t038LtU2gzbqkQ',
    appId: '1:109677064278:web:c8c4c301eb18f1ef298bf7',
    messagingSenderId: '109677064278',
    projectId: 'spotify-f4d39',
    authDomain: 'spotify-f4d39.firebaseapp.com',
    storageBucket: 'spotify-f4d39.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKWH7GtxGGhyi9eF8hfvBK7J5ryfmr_gU',
    appId: '1:109677064278:ios:d2e70e59f7409962298bf7',
    messagingSenderId: '109677064278',
    projectId: 'spotify-f4d39',
    storageBucket: 'spotify-f4d39.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqY7Eo6UOMRBtxL4x5t038LtU2gzbqkQ',
    appId: '1:109677064278:web:458a1bae774f60e7298bf7',
    messagingSenderId: '109677064278',
    projectId: 'spotify-f4d39',
    authDomain: 'spotify-f4d39.firebaseapp.com',
    storageBucket: 'spotify-f4d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKWH7GtxGGhyi9eF8hfvBK7J5ryfmr_gU',
    appId: '1:109677064278:ios:d2e70e59f7409962298bf7',
    messagingSenderId: '109677064278',
    projectId: 'spotify-f4d39',
    storageBucket: 'spotify-f4d39.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz34qy2E3grd6dhZ7ZxoPkTeVgTPYyfQI',
    appId: '1:109677064278:android:4645c1add14a60f9298bf7',
    messagingSenderId: '109677064278',
    projectId: 'spotify-f4d39',
    storageBucket: 'spotify-f4d39.firebasestorage.app',
  );

}